---
- name: Install common dev tools
  hosts: all
  roles:
    - { role: jvalentini.common, tags: common }
  vars:
    tern_dest: "{{ home }}/tern"
  tasks:
    - name: add apt repos and update
      apt_repository: repo={{ item }} state=present update_cache=yes
      with_items:
        - ppa:git-core/ppa
        - ppa:ansible/ansible
        - ppa:leolik/leolik
        - ppa:amandeepgrewal/notifyosdconfig
        - ppa:mc3man/trusty-media
        - "deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
      become: true
      tags: apt, apt_repo
    - name: apt-get upgrade
      command: apt-get upgrade -y
      become: true
      tags: apt, apt_upgrade
    - name: install apt packages
      apt: name={{ item }} state=latest update_cache=yes
      with_items:
        - build-essential
        - software-properties-common
        - python-software-properties
        - ubuntu-restricted-extras
        - dkms
        - terminator
        - curl
        - git
        - corkscrew
        - zsh
        - xmonad
        - xmobar
        - xscreensaver
        - offlineimap
        - gnome-panel
        - xmonad
        - xmobar
        - xscreensaver
        - libaio1
        - linux-headers-generic
        - virtualbox-dkms
        - virtualbox-5.0
        - python
        - python-dev
        - python-pip
        - pylint
        - ipython
        - rbenv
        - ruby-dev
        - redis-server
        - sqlite
        - pidgin
        - pidgin-plugin-pack
        - openssh-client
        - openssh-server
        - php5
        - htop
        - default-jre
        - jq
        - vlc
        - vlc-plugin-notify
        - silversearcher-ag
        - gcc-multilib
        - autoconf
        - automake
        - autotools-dev
      become: true
      tags: apt, apt_install
    - git: repo=https://github.com/rbenv/rbenv.git dest={{ rbenv_dest }}
    - shell: cd {{ rbenv_dest }} && src/configure && make -C src
    - git: repo=https://github.com/rbenv/ruby-build.git dest={{ rbenv_dest }}/plugins/ruby-build
    - command: rbenv install 2.3.0
    - name: install tern, a js code analyzer
      git: repo=https://github.com/ternjs/tern.git dest={{ tern_dest }}
      tags: tern
    - command: npm install
      become: true
      tags: tern
